"""Block input construction for this platform.

Generated by the factory WRITER. Handlers call prepare_block_input (via the
fail-closed execute wrapper) so domain records become block-acceptable
payloads without requiring the caller to know about channel/steps/paths.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
from typing import Any, Dict, List, Optional, Sequence, Tuple

STORE_BLOCK_DEFAULT_ACTIONS = {'analytics': 'track_event', 'audit': 'log', 'capture': 'extract', 'capture_v2': 'extract', 'dashboard': 'render', 'database': 'query', 'document_engine': 'parse', 'event_bus': 'publish', 'formula_executor': 'execute', 'formula_executor_v2': 'execute', 'notification': 'send', 'queue': 'enqueue', 'team': 'create_team', 'validation': 'validate', 'vector_search': 'search', 'workflow': 'run', 'spec_analyzer': 'analyze', 'recommendation_template': 'apply_template', 'readiness_engine': 'score', 'storage': 'store', 'estate_registry': 'register', 'estate_maintenance': 'plan_work', 'evidence_verifier': 'verify', 'portfolio_rollup': 'aggregate', 'knowledge': 'search'}


def default_block_action(block_id, default_actions=None):
    """Keyword action for execute(..., action=). Never invent from payload."""
    bid = str(block_id or "").strip()
    if isinstance(default_actions, dict):
        cand = default_actions.get(bid)
        if isinstance(cand, str) and cand.strip():
            return cand.strip()
    mapped = STORE_BLOCK_DEFAULT_ACTIONS.get(bid)
    if isinstance(mapped, str) and mapped.strip():
        return mapped.strip()
    return None


_QUEUE_INT_KEYS = (
    "id",
    "priority",
    "delay",
    "delay_seconds",
    "timeout",
    "visibility_timeout",
    "attempts",
    "max_attempts",
    "retry_count",
    "item_id",
)
_DOC_PATH_KEYS = (
    "file_path",
    "pdf_path",
    "docx_path",
    "xlsx_path",
    "attachment_path",
    "document_path",
    "path",
)
_TEAM_STRING_KEYS = ("user_id", "name", "slug", "role", "email", "plan", "permission")
_TOPIC_KEYS = ("topic", "event", "event_type", "event_name", "reminder_type")
_MINIMAL_PDF = (
    b"%PDF-1.1\n"
    b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
    b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
    b"3 0 obj<</Type/Page/MediaBox[0 0 3 3]>>endobj\n"
    b"trailer<</Size 4/Root 1 0 R>>\n"
)
_SYNTH_DOC_PATH = None
_SKIP = frozenset(
    {
        "ok",
        "error",
        "capability",
        "id",
        "status",
        "result",
        "results",
        "payload",
        "action",
        "block",
        "blocks",
        "channel",
        "message",
        "steps",
        "team_id",
    }
)


def split_execute_action(
    payload: Any,
    *,
    action: Optional[str] = None,
    default_action: Optional[str] = None,
) -> Tuple[Optional[str], Dict[str, Any]]:
    data = dict(payload) if isinstance(payload, dict) else (
        {} if payload is None else {"value": payload}
    )
    inner = data.get("input") if isinstance(data.get("input"), dict) else {}

    def _usable(value):
        if isinstance(value, str) and value.strip():
            return value
        return None

    resolved = (
        _usable(action)
        or _usable(data.get("action"))
        or _usable(inner.get("action"))
        or _usable(default_action)
    )
    data.pop("action", None)
    if isinstance(data.get("input"), dict):
        cleaned = dict(data["input"])
        cleaned.pop("action", None)
        data["input"] = cleaned
    return resolved, data


def prepare_block_input(
    block_id: str,
    domain: Any,
    *,
    action: Optional[str] = None,
    roster: Sequence[str] = (),
    product_name: str = "platform",
    entity: Optional[str] = None,
    default_actions: Optional[Dict[str, str]] = None,
) -> Dict[str, Any]:
    _resolved, data = split_execute_action(domain, action=action)
    bid = str(block_id or "")
    merged_actions = dict(STORE_BLOCK_DEFAULT_ACTIONS)
    if default_actions:
        merged_actions.update(default_actions)
    if bid == "notification":
        return _for_notification(data, roster)
    if bid == "workflow":
        return _for_workflow(
            data,
            roster,
            product_name=product_name,
            entity=entity,
            default_actions=merged_actions,
        )
    if bid == "team":
        return _for_team(data, product_name=product_name)
    if bid == "document_engine":
        return _for_document_engine(data)
    if bid == "analytics":
        return _for_analytics(data)
    if bid == "event_bus":
        return _for_event_bus(data, roster)
    if bid == "database":
        return _for_database(data, entity=entity)
    if bid == "queue":
        return _for_queue(data)
    if bid == "dashboard":
        return _for_dashboard(data)
    return data


def _summary_message(data: Dict[str, Any]) -> str:
    parts = [
        f"{key}={value}"
        for key, value in data.items()
        if isinstance(value, (str, int, float, bool)) and key not in _SKIP
    ]
    return (("; ".join(parts)).strip() or "platform notification")[:500]


def _for_dashboard(data: Dict[str, Any]) -> Dict[str, Any]:
    out = dict(data)
    inner = out.get("input") if isinstance(out.get("input"), dict) else {}
    status = out.get("status") if out.get("status") is not None else inner.get("status")
    if not (isinstance(status, str) and status.strip()):
        out["status"] = "open"
    elif not out.get("status"):
        out["status"] = status
    return out


def _notification_channel(value, data=None):
    raw = str(value or "").strip().lower()
    payload = data if isinstance(data, dict) else {}
    if raw == "mcp":
        return "mcp"
    if raw == "email":
        to = payload.get("to") or payload.get("email")
        if isinstance(to, str) and to.strip() and "@" in to:
            return "email"
        return "mcp"
    if raw == "webhook":
        url = payload.get("url") or payload.get("webhook_url")
        if isinstance(url, str) and url.startswith(("http://", "https://")):
            return "webhook"
        return "mcp"
    if raw == "slack":
        if payload.get("webhook_url") or payload.get("slack_webhook_url"):
            return "slack"
        return "mcp"
    return "mcp"


def _for_notification(data: Dict[str, Any], roster: Sequence[str]) -> Dict[str, Any]:
    out = dict(data)
    out["channel"] = _notification_channel(out.get("channel"), out)
    if not out.get("message"):
        body = out.get("body")
        out["message"] = (
            body if isinstance(body, str) and body.strip() else _summary_message(data)
        )
    if str(out.get("channel")).lower() == "mcp" and not out.get("block") and not out.get("tool"):
        peers = [b for b in roster if b and b != "notification"]
        out["block"] = peers[0] if peers else "notification"
    return out


def _workflow_step_block(step):
    for key in ("block", "block_id", "name"):
        value = step.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _step_action(block_id, default_actions):
    return default_block_action(block_id, default_actions)


def _shape_workflow_steps(
    steps,
    roster,
    *,
    product_name,
    entity,
    default_actions,
    fallback_domain,
):
    shaped = []
    for step in steps:
        if not isinstance(step, dict):
            shaped.append(step)
            continue
        item = dict(step)
        bid = _workflow_step_block(item)
        if not bid:
            shaped.append(item)
            continue
        raw = item.get("input")
        payload = raw if isinstance(raw, dict) else fallback_domain
        item["block"] = bid
        item["input"] = prepare_block_input(
            bid,
            payload,
            roster=roster,
            product_name=product_name,
            entity=entity,
            default_actions=default_actions,
        )
        if not item.get("action"):
            action = _step_action(bid, default_actions)
            if action:
                item["action"] = action
        shaped.append(item)
    return shaped


def _workflow_result_payload(data, steps=None):
    if isinstance(data, dict):
        existing = data.get("result")
        if existing not in (None, ""):
            return existing
    chain = steps
    if chain is None and isinstance(data, dict):
        chain = data.get("steps")
    for step in chain or ():
        if not isinstance(step, dict):
            continue
        inner = step.get("input")
        if isinstance(inner, dict) and inner:
            return dict(inner)
        if inner not in (None, ""):
            return inner
    if not isinstance(data, dict):
        return {"reference": "record"}
    scalars = {
        key: value
        for key, value in data.items()
        if key not in {
            "steps",
            "action",
            "result",
            "results",
            "input",
            "ok",
            "error",
            "block",
            "blocks",
        }
        and value not in (None, "")
    }
    return scalars or {"reference": data.get("reference") or "record"}


def _ensure_workflow_result(data, steps=None):
    out = dict(data) if isinstance(data, dict) else {}
    if steps is not None:
        out["steps"] = list(steps)
    if out.get("result") not in (None, ""):
        return out
    out["result"] = _workflow_result_payload(out, out.get("steps"))
    return out


def _for_workflow(
    data: Dict[str, Any],
    roster: Sequence[str],
    *,
    product_name: str = "platform",
    entity: Optional[str] = None,
    default_actions: Optional[Dict[str, str]] = None,
) -> Dict[str, Any]:
    out = dict(data)
    steps = out.get("steps")
    if isinstance(steps, list) and steps:
        out["steps"] = _shape_workflow_steps(
            steps,
            roster,
            product_name=product_name,
            entity=entity,
            default_actions=default_actions,
            fallback_domain=data,
        )
        return _ensure_workflow_result(out)
    peers = [b for b in roster if b and b != "workflow"]
    built: List[Dict[str, Any]] = []
    for block in peers[:3]:
        step = {
            "block": block,
            "input": prepare_block_input(
                block,
                data,
                roster=roster,
                product_name=product_name,
                entity=entity,
                default_actions=default_actions,
            ),
        }
        action = _step_action(block, default_actions)
        if action:
            step["action"] = action
        built.append(step)
    if not built:
        built.append({"block": "workflow", "input": dict(data)})
    out["steps"] = built
    return _ensure_workflow_result(out)


def _looks_minted_team_id(value):
    if not isinstance(value, str):
        return False
    body = value[5:] if value.startswith("team_") else ""
    return len(body) >= 8 and all(c in "0123456789abcdefABCDEF" for c in body)


def _platform_team_id():
    try:
        from app.preconditions import resource_id
    except Exception:
        return None
    tid = resource_id("team")
    if tid:
        return str(tid)
    try:
        from app.preconditions import ensure_all

        ensure_all()
    except Exception:
        return None
    tid = resource_id("team")
    return str(tid) if tid else None


def _for_team(data: Dict[str, Any], *, product_name: str = "platform") -> Dict[str, Any]:
    out = dict(data)
    for key in _TEAM_STRING_KEYS:
        if key in out and out[key] is None:
            out.pop(key)
    slug_base = re.sub(r"[^a-z0-9-]+", "-", (product_name or "platform").lower()).strip("-")
    slug_base = slug_base or "platform"
    out.setdefault("user_id", "system")
    out.setdefault("name", f"{product_name or 'platform'} team")
    out.setdefault("slug", f"{slug_base}-team")
    minted = _platform_team_id()
    current = out.get("team_id")
    if minted and (not current or not _looks_minted_team_id(current)):
        out["team_id"] = minted
    for key in _TEAM_STRING_KEYS:
        if key in out and out[key] is None:
            out.pop(key)
        elif key in out and not isinstance(out[key], str):
            out[key] = str(out[key])
    return out


def _existing_file_path(value):
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        return value if os.path.isfile(value) else None
    except OSError:
        return None


def _synthesized_document_path():
    global _SYNTH_DOC_PATH
    if _SYNTH_DOC_PATH and os.path.isfile(_SYNTH_DOC_PATH):
        return _SYNTH_DOC_PATH
    fd, path = tempfile.mkstemp(prefix="platform-doc-", suffix=".pdf")
    with os.fdopen(fd, "wb") as handle:
        handle.write(_MINIMAL_PDF)
    _SYNTH_DOC_PATH = path
    return path


def _for_document_engine(data: Dict[str, Any]) -> Dict[str, Any]:
    out = dict(data)
    inner = out.get("input") if isinstance(out.get("input"), dict) else {}
    for key in _DOC_PATH_KEYS:
        if isinstance(out.get(key), dict):
            out.pop(key)
        elif key not in out and _existing_file_path(inner.get(key)):
            out[key] = inner[key]
    existing = None
    for key in _DOC_PATH_KEYS:
        existing = _existing_file_path(out.get(key))
        if existing:
            out.setdefault("file_path", existing)
            out.setdefault("pdf_path", existing)
            break
    text = out.get("text")
    if not (isinstance(text, str) and text.strip()):
        lines = [
            f"{key}: {value}"
            for key, value in data.items()
            if isinstance(value, (str, int, float, bool))
        ]
        out["text"] = "\n".join(lines) if lines else json.dumps(data, default=str)
    if existing:
        return out
    path = _synthesized_document_path()
    out["file_path"] = path
    out["pdf_path"] = path
    return out


def _for_analytics(data: Dict[str, Any]) -> Dict[str, Any]:
    out = dict(data)
    inner = out.get("input") if isinstance(out.get("input"), dict) else {}
    for key in ("metric", "value"):
        if key not in out and key in inner:
            out[key] = inner[key]
    if not out.get("metric"):
        for key, value in data.items():
            if key != "input" and isinstance(value, str) and value:
                out["metric"] = key
                break
        out.setdefault("metric", "event")
    if out.get("value") is None:
        for key, value in data.items():
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                out["value"] = value
                break
        out.setdefault("value", 1)
    return out


def _topic_from_domain(data):
    slug = re.sub(r"[^a-zA-Z0-9_.-]+", ".", _summary_message(data)).strip(".")
    return (slug or "platform.event")[:80]


def _for_event_bus(data, roster=()):
    inner = data.get("input") if isinstance(data.get("input"), dict) else {}
    topic = data.get("topic") or inner.get("topic")
    if not (isinstance(topic, str) and topic.strip()):
        for key in _TOPIC_KEYS:
            if key == "topic":
                continue
            cand = data.get(key) if data.get(key) is not None else inner.get(key)
            if isinstance(cand, str) and cand.strip():
                topic = cand.strip()
                break
        else:
            topic = _topic_from_domain(data)
    topic = str(topic).strip()
    payload = data.get("payload") if isinstance(data.get("payload"), dict) else None
    if payload is None and isinstance(inner.get("payload"), dict):
        payload = inner["payload"]
    if not isinstance(payload, dict):
        payload = {
            key: value
            for key, value in data.items()
            if key not in _SKIP and isinstance(value, (str, int, float, bool))
        } or {"topic": topic}
    message = data.get("message") if isinstance(data.get("message"), str) else ""
    if not str(message).strip():
        inner_msg = inner.get("message")
        message = inner_msg if isinstance(inner_msg, str) and inner_msg.strip() else _summary_message(data)
    channel = _notification_channel(
        data.get("channel") if data.get("channel") is not None else inner.get("channel"),
        data,
    )
    return {
        "topic": topic,
        "payload": dict(payload),
        "data": dict(payload),
        "event": topic,
        "message": str(message).strip() or _summary_message(data),
        "channel": channel,
        "block": "event_bus",
        "tool": "event_bus",
    }


def _coerce_int(value):
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, str) and value.strip().lstrip("-").isdigit():
        return int(value.strip())
    return None


def _for_queue(data: Dict[str, Any]) -> Dict[str, Any]:
    out = dict(data)
    inner = out.get("input") if isinstance(out.get("input"), dict) else {}
    for key in _QUEUE_INT_KEYS:
        raw = out[key] if key in out else inner.get(key)
        if raw is None:
            continue
        coerced = _coerce_int(raw)
        if coerced is not None:
            out[key] = coerced
    if out.get("item_id") is None:
        aliased = _coerce_int(out.get("id"))
        if aliased is not None:
            out["item_id"] = aliased
    elif out.get("id") is None:
        aliased = _coerce_int(out.get("item_id"))
        if aliased is not None:
            out["id"] = aliased
    for key in ("priority", "delay", "delay_seconds", "timeout", "visibility_timeout", "attempts", "max_attempts", "retry_count"):
        if key in out and _coerce_int(out[key]) is None:
            out[key] = 0
    for key in ("id", "item_id"):
        if key in out and _coerce_int(out[key]) is None:
            out.pop(key)
    if "payload" not in out and "item" not in out:
        out["payload"] = {
            key: value
            for key, value in data.items()
            if key not in _SKIP
            and key not in {"payload", "item", "input"}
            and isinstance(value, (str, int, float, bool))
        }
    out.setdefault("priority", 0)
    return out


def _usable_table_name(value):
    if isinstance(value, str) and re.match(r"^[A-Za-z_][\w]*$", value.strip()):
        return value.strip()
    return None


_SQL_RECORDS_TABLE = re.compile(
    r"\b(FROM|INTO|UPDATE|JOIN|TABLE)\s+records\b",
    re.IGNORECASE,
)


def _retarget_records_sql(sql, entity):
    return _SQL_RECORDS_TABLE.sub(lambda match: f"{match.group(1)} {entity}", sql)


def _for_database(data: Dict[str, Any], *, entity: Optional[str] = None) -> Dict[str, Any]:
    out = dict(data)
    inner = out.get("input") if isinstance(out.get("input"), dict) else {}
    for key in ("sql", "table", "table_name", "values"):
        if key not in out and key in inner:
            out[key] = inner[key]
    entity_table = _usable_table_name(entity)
    sql = out.get("sql")
    if isinstance(sql, str) and sql.strip():
        if entity_table and _SQL_RECORDS_TABLE.search(sql):
            out["sql"] = _retarget_records_sql(sql, entity_table)
            out["table"] = entity_table
        return out
    table = _usable_table_name(out.get("table") or out.get("table_name"))
    if table == "records" and entity_table:
        table = entity_table
    if not table:
        for key in ("entity", "table", "table_name"):
            table = _usable_table_name(out.get(key) or inner.get(key))
            if table and table != "records":
                break
            if table == "records" and entity_table:
                table = entity_table
                break
    if not table:
        table = entity_table
    if not table:
        table = "records"
    out["table"] = table
    if not isinstance(out.get("values"), dict):
        values = {
            key: value
            for key, value in data.items()
            if key not in _SKIP
            and key not in {"sql", "table", "table_name", "values", "input", "entity"}
            and isinstance(value, (str, int, float, bool))
        }
        if values:
            out["values"] = values
    return out


# Default actions resolved against the vendored slices this product
# actually binds (see docs/blockers.json): the Store ``validation``
# slice answers validate_dependencies/validate_block (not ``validate``)
# and the ``memory`` slice answers set/get/delete/exists.
STORE_BLOCK_DEFAULT_ACTIONS.update({
    'analytics': 'track_event',
    'audit': 'log',
    'capture': 'extract',
    'dashboard': 'render',
    'database': 'query',
    'event_bus': 'publish',
    'formula_executor': 'execute',
    'knowledge': 'search',
    'memory': 'set',
    'notification': 'send',
    'queue': 'enqueue',
    'validation': 'validate_dependencies',
})
